export const dataF = [
  {
    nameDestinatary: "Camilo Mora",
    destiny: "Bogota",
    direction: "calle 40 sur 11-79 este",
    code: 54514,
    state: "Cancelar",
  },
  {
    nameDestinatary: "Pepito Manuelito",
    destiny: "Pasto",
    direction: "calle 32 sur 10-87 este",
    code: 23262,
    state: "Cancelado",
  },
  {
    nameDestinatary: "Pepito pepe",
    destiny: "Manizales",
    direction: "KR 10 sur 8-45 sur",
    code: 15477,
    state: "Cancelar",
  },
  {
    nameDestinatary: "Pepito lopez",
    destiny: "Bogota",
    direction: "KR 22 sur 11-79 sur-este",
    code: 32415,
    state: "Entregado",
  },
  {
    nameDestinatary: "Pepito Mora",
    destiny: "Bogota",
    direction: "calle 44 sur 11-79 norte",
    code: 12875,
    state: "Entregado",
  },
  {
    nameDestinatary: "Pepito peña",
    destiny: "Medellin",
    direction: "calle 38 norte 89-84 este",
    code: 12548,
    state: "Entregado",
  },
  {
    nameDestinatary: "Pepito fresa",
    destiny: "Cali",
    direction: "KR 44 sur 11-79 este",
    code: 26875,
    state: "Cancelado",
  },
];